name: Common build and publish workflow

on: 
  workflow_call:
    inputs:
      target-dir:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Build code
        run: |
          npm run build -w packages/${{ inputs.target-dir }}
      - run: npm publish --access public -w packages/${{ inputs.target-dir }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}